apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-demo
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: podinfo
